### ISSUE TITLE
Images are not showing up

### ISSUE THREAD

**Issue by oifj34f34f** [redlib-org/redlib#25]
## Screenshots

Redlib:

![](https://github.com/redlib-org/redlib/assets/128177553/605bde9c-a47a-4b8c-8a7c-482ab74181b0)

Reddit:

![](https://github.com/redlib-org/redlib/assets/128177553/00139597-605c-47a1-87d6-49e94df24a12)

## Examples

In the comment: https://libreddit.bus-hit.me/r/travisscott/comments/135ev4e/travis_scott_getting_kicked_out_of_his_own/jijsjr7/?context=3

In the post: https://libreddit.bus-hit.me/r/spotify/comments/138f5gk/psa_how_to_get_spotify_desktop_back_to_the_old/

**Comment by oifj34f34f** [comment]
Sorry, forgot to read the latest commits. I guess it should be fixed in the next release

**Comment by sigaloid** [comment]
I don't believe this specifically is fixed in the most recent version so I have reopened this. 

Basically a regular link to an image should be replaced with an img, as reddit does

**Comment by sigaloid** [comment]
This is slightly more advanced then first thought, can't just go through the normal format_url path, I have to catch any `<a href="(any reddit link)>` instead of simply regex rip and replace. :thinking: will play around with some fixes

**Comment by ButteredCats** [comment]
With a slight bit of fucking about I've achieved a really shitty and incomplete way of doing this, but one that's technically functional nonetheless.

In `utils.rs` on line 886 change
```
REDDIT_REGEX.replace_all(input_text, r#"href="/"#)
			.to_string();
``` 
to
```
REDDIT_REGEX.replace_all(input_text, r#"href="/"#)
			.to_string()
			.replace("a href=\"https://preview.redd.it", "img src=\"https://preview.redd.it");
``` 

and add
```
.comment_right img {
	width: 50%;
}
```
into `style.css`, doesn't matter where.

This does make the pictures show up, but the text for the link is still left, and because there's no `a href=` you can't just click on them to open them up.

I'm sure this isn't the right avenue to be approaching this from, but I figured I may as well comment with it in the hope it sparks discussion for this. This isn't the first time I've taken a crack at this, and this is unfortunately the best I've been able to come up with.
