### ISSUE TITLE
🐛 Bug Report: Website down?

### ISSUE THREAD

**Issue by dtantono** [redlib-org/redlib#54]
## Describe the bug

 I tried to open the official instance, https://redlib.matthew.science/. But, it is stuck on loop. Is it down?

## Steps to reproduce the bug

1. Go to https://redlib.matthew.science/
2. it does not work

## What's the expected behavior?

 it should work

**Comment by sigaloid** [comment]
Fixed - just needed a reboot.

I might mention here - the official instance, while being the one I am running, cannot have its uptime guaranteed at **all**. My hoster could go down at any time and I can't rush to triage it. There are a number of other instances you can use. Notably, you can visit https://farside.link/redlib to switch to any live instance.

That being said, it being down this particular time was actually an interesting error - maybe https://github.com/redlib-org/redlib/issues/22 since I wasn't running the latest image tag.
