### ISSUE TITLE
🐛 Bug Report: Releases not being generated ... 

### ISSUE THREAD

**Issue by ThePixelDeveloper** [redlib-org/redlib#74]
## Describe the bug
Redlib releases not being generated ... 

## Steps to reproduce the bug
Take a look at the [release workflow](https://github.com/redlib-org/redlib/actions/runs/8149558786), you can see the upload steps aren't working.

## What's the expected behavior?
Release to be generated, otherwise the Dockerfile doesn't work with the `${TARGET}` ARG.

## Additional context / screenshot
n/a

**Comment by Wave6677** [comment]
https://quay.io/repository/redlib/redlib

The docker image on quay has not been updated for 2 versions. The current docker image on quay is v0.31.0, and the latest on github is v0.31.2. The current v31 image doesn't work, and causes a 404 Not Found error from the reverse proxy. No out of the ordinary logs in the logs. Can be provided if need be.

**Comment by sigaloid** [comment]
Yes, I am considering reverting to the previous release workflow... :thinking: probably before next release.

**Comment by bo0tzz** [comment]
@sigaloid I believe you've now got the rust build & artifact upload working, but container images still aren't being pushed. If you want a hand with that let me know & I can open a PR.

**Comment by Silvenga** [comment]
Yeah, @sigaloid, let us know where we can help.

I've been looking at the pipelines, it seems doable to stick all of the artifacts (docker and the binaries) into a single multi-job pipeline that runs everywhere (only enabling releasing on release/tag creation). That'll make most of the code always run, would also aid in detecting issues quicker (every pr, instead of every release). It could also automate adding the docker image digests into the releases page, and support creating docker files on pr's (maybe only uploaded to GH Containers Registry?), which would be very cool, to let some users beta test a pr.

**Comment by sigaloid** [comment]
Honestly, the problem is pretty simple, it's building one binary but our old workflow expected three, so the image registry hasn't worked in a while. 

I'm not experienced at ALL with GH actions, and having to increment versions every single time I want to test due to crates.io is painful. So if you see a clean and logical way to fix it, please PR!
