### ISSUE TITLE
🐛 Bug Report: images with captions are not well implemented

### ISSUE THREAD

**Issue by grandpa1946** [redlib-org/redlib#91]
## Describe the bug

images with captions are not well implemented 
## Steps to reproduce the bug
view any reddit post with preview images, like this one https://www.reddit.com/r/Piracy/comments/18qt68n/guide_how_to_never_use_torrent_sites_ever_again (.json)

1. Go to any redlib instance and visit this post
2. Scroll down and see that every image has the same caption and is also the same
3. See error
## What's the expected behavior?

redlib implements the images in the post with captions in a better way
## Additional context / screenshot

maybe this thing is causing the issue
`&amp;#x200B;`

**Comment by ButteredCats** [comment]
The images and captions all being the same was already fixed in https://github.com/redlib-org/redlib/pull/80. It's just that most instances are running the release version instead of the latest git commits.

However even with the latest git commits the captions wont show up because when I made the images embed I apparently overlooked that. So I just opened https://github.com/redlib-org/redlib/pull/92 to make sure the captions appear as well when they embed too.

**Comment by grandpa1946** [comment]
> The images and captions all being the same was already fixed in #80. It's just that most instances are running the release version that doesn't include that code instead of the latest git commits which do.
> 
> However even with the latest git commits the captions wont show up because when I made the images embed I apparently overlooked that. So I just opened #92 to make sure the captions appear as well when they embed too.

tysm!
